name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: scaleleap-dev

    steps:
    - uses: actions/checkout@v3
    - run: docker -v
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test:$(date +%s)
