# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: scaleleap-dev
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - run: ls -la /home/runner/_work
      - run: ls -la ~/
      - run: ls -la ~/.local/share/pnpm/store
      - run: pnpm install
      - run: ls -la ~/.local/share/pnpm/store
